const data = [
  {
    id: 1,
    name: 'Шпаклевка финишная полимерная GT-53 GERKULES',
    description: '',
    imageURL: `/products/shpatlevka-gerkules.jpeg`,
    price: 890,
  },
  {
    id: 2,
    name: 'Клей для пенобетона Профикс-Магнтит 25кг',
    description: '',
    imageURL: `/products/kley-dlya-penobetona-profix-magnit.jpg`,
    price: 400,
  },
  {
    id: 3,
    name: 'Пескобетон Саха-Профикс М150 25кг',
    description: '',
    imageURL: `/products/peskobeton-sakha-profix-m150.jpg`,
    price: 360,
  },
  {
    id: 4,
    name: 'Пескобетно Саха-Профикс М200 25кг',
    description: '',
    imageURL: `/products/peskobeton-sakha-profix-m200.jpg`,
    price: 450,
  },
  {
    id: 5,
    name: 'Клей плиточный усиленный Саха-Профикс 25кг',
    description: '',
    imageURL: `/products/kley-plitochnyi-usilennyi-sakha-profix.jpg`,
    price: 500,
  },
  {
    id: 6,
    name: 'Клей плиточный стандарт Саха-Профикс 25кг',
    description: '',
    imageURL: `/products/kley-plitochnyi-standart-sakha-profix.jpg`,
    price: 460,
  },
  {
    id: 7,
    name: 'Цемент М500 20кг',
    description: '',
    imageURL: `/products/cement-m500-20kg.jpg`,
    price: 420,
  },
  {
    id: 8,
    name: 'Цемент М400 10кг',
    description: '',
    imageURL: `/products/cement-m400-10kg.jpg`,
    price: 250,
  },
  {
    id: 9,
    name: 'Ровнитель для пола ПЛАТО (ПРОФИКС) 25кг',
    description: '',
    imageURL: `/products/rovnitel'-dlya-pola-plato-(profix).jpg`,
    price: 425,
  },
  {
    id: 10,
    name: 'Штукатурка гипсовая универсальная ROTBAND KNAUF 30кг',
    description: '',
    imageURL: `/products/shtukaturka-gipsovaya-universal-ROTBAND-KNAUF-30kg.jpg`,
    price: 840,
  },
  {
    id: 11,
    name: 'Пенополистирол М25 10мм (в пачке 6шт цена за шт)',
    description: '',
    imageURL: `/products/penopolistirol.jpg`,
    price: 850,
  },
  {
    id: 12,
    name: 'Пенополистирол М35 10мм (в пачке 6шт цена за шт)',
    description: '',
    imageURL: `/products/penopolistirol.jpg`,
    price: 1300,
  },
  {
    id: 13,
    name: 'Пенополистирол М25 5мм (в пачке 12шт цена за шт)',
    description: '',
    imageURL: `/products/penopolistirol.jpg`,
    price: 425,
  },
  {
    id: 14,
    name: 'Пенополистирол М35 5мм (в пачке 12шт цена за шт)',
    description: '',
    imageURL: `/products/penopolistirol.jpg`,
    price: 650,
  },
  {
    id: 15,
    name: 'ОСБ на 12мм',
    description: '',
    imageURL: `/products/OSB-na-12mm.jpg`,
    price: 1700,
  },
  {
    id: 16,
    name: 'Цемент М400(32,5Б) 50кг',
    description: '',
    imageURL: `/products/cement-m400(32,5B)-50kg.jpg`,
    price: 750,
  },
  {
    id: 17,
    name: 'Цемент М500(42,5Н) 50кг',
    description: '',
    imageURL: `/products/cement-m500(42,5N)-50kg.jpg`,
    price: 800,
  },
  {
    id: 18,
    name: 'Наливной пол GERKULES 30кг.',
    description: '',
    imageURL: `/products/nalivnoy-pol-GERKULES-30kg.jpg`,
    price: 980,
  },
  {
    id: 19,
    name: 'Арматура Стеклокомпозитная d-10 50м',
    description: '',
    imageURL: `/products/armatura-steklokompozitnaya-d-10-50m.jpg`,
    price: 2500,
  },
  {
    id: 20,
    name: 'Арматура Стеклокомпозитная d-12 50м',
    description: '',
    imageURL: `/products/armatura-steklokompozitnaya-d-12-50m.jpg`,
    price: 3000,
  },
  {
    id: 21,
    name: 'Арматура Стеклокомпозитная d-10 6.25м',
    description: '',
    imageURL: `/products/armatura-steklokompozitnaya-d-10-6,25m.jpg`,
    price: 325,
  },
  {
    id: 22,
    name: 'Арматура Стеклокомпозитная d-12 6.25м',
    description: '',
    imageURL: `/products/armatura-steklokompozitnaya-d-12-6,25m.jpg`,
    price: 395,
  },
  {
    id: 23,
    name: 'Цемент М400 МКР-1,5тн',
    description: '',
    imageURL: `/products/cement-m400-MKR-1,5tn.jpg`,
    price: 22000,
  },
  {
    id: 24,
    name: 'Цемент М500 МКР-1,5тн',
    description: '',
    imageURL: `/products/cement-m500-MKR-1,5tn.jpg`,
    price: 23000,
  },
  {
    id: 25,
    name: 'Сетка кладочная 100*100мм 2*3м',
    description: '',
    imageURL: `/products/setka-kladochnaya-100*100-2*3m.jpg`,
    price: 940,
  },
  {
    id: 26,
    name: 'Сетка кладочная 50*50мм 1*2м',
    description: '',
    imageURL: `/products/setka-kladochnaya-50*50-1*2m.jpg`,
    price: 550,
  },
  {
    id: 27,
    name: 'Сетка кладочная 50*50мм 2*3м',
    description: '',
    imageURL: `/products/setka-kladochnaya-100*100-2*3m.jpg`,
    price: 1600,
  },
  {
    id: 28,
    name: 'Акриловая грунтовка 10кг покрытие 60-100кв.м',
    description: '',
    imageURL: `/products/akrilovaya-gruntovka-10kg.jpg`,
    price: 850,
  },
  {
    id: 29,
    name: 'Акриловая грунтовка 5кг покрытие 30-50кв.м',
    description: '',
    imageURL: `/products/akrilovaya-gruntovka-5kg.jpg`,
    price: 450,
  },
];

export default data;
